### PR TITLE
#165305256 Configure Authors Haven to use PostgreSQL as DB Engine

### PR DESCRIPTION
**Pull request by Benkimeric**
#### What does this PR do?
Change the database engine from SQLite to Postgres
#### Description of Task to be completed?

- Change the database engine for the application from SQLite to Postgres
- Pip install psycopg2-binary to allow the app to connect to Postgres database
- Add `.env_example` file 
#### How should this be manually tested?
- Clone the repository `https://github.com/andela/ah-the-jedi-backend.git`
- Fetch all branches by using the command: `git pull`
- checkout to the branch `git checkout ch-postgres-db-setup-162948903`
- create virtual  environment `python -m venv env`
- activate virtual environment `source env/bin/activate`
- Install requirements `pip install -r requirements.txt`
- Download and install postgreSQL globally: link [here](https://www.postgresql.org/download/)
- create a Postgres database on your local machine
- Make a copy of `.env_example` as  `.env` and fill all the variables
- run `python manage.py makemigrations`
- then `python manage.py migrate`
- Run `python manage.py runserver`

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#165305256](https://www.pivotaltracker.com/story/show/165305256)
#### Image of Postman After successful user signup
Screenshot 2019-04-23 at 13 08 52

#### Image of Postgres Database Users Table After Successful User Signup
Screenshot 2019-04-23 at 13 06 46

#### Questions:
Any feedback?

### CODE REVIEW

**Review by katherine95 — APPROVED** [review]
Great work on following pep8 standards.

**Review by Siffersari — APPROVED** [review]
I love how detailed and well formatted your PR is. I also like that you included a .env-example file to indicate which variables should be set for configuration. Good job migrating the database to use PostgreSQL.

**Review by AlvinMugambi — APPROVED** [review]
The PR is well detailed.

**Review by jkamz — APPROVED** [review]

**Review by rnjane — CHANGES_REQUESTED** [review]
Good work @Benkimeric. Kindly add database setup instructions in the readme.

**Review by rnjane — APPROVED** [review]

**Pull request merged**
