### PR TITLE
#165305255 Integrate TravisCI with readme badge.

### PR DESCRIPTION
**Pull request by katherine95**
#### What does this PR do?
Integrate TravisCI with the project and include TravisCI badge in Readme.MD file.
#### Description of Task to be completed?
- Add the project repository to Travis CI repositories.
- Create `.travis.yml` file with relevant settings and commands.
- Push the branch to Github.
- Wait for the build of the branch to be complete.
#### How should this be manually tested?
- Clone the repository: `git clone https://github.com/andela/ah-the-jedi-backend.git`
- Fetch origin to get all branches: `git fetch origin`
- Checkout to the working branch  `git checkout ch-integrate-travisCI-badge-165305255`
- Check TravisCI webpage for build status: link [here](https://travis-ci.com/andela/ah-the-jedi-backend)
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#165305255](https://www.pivotaltracker.com/story/show/165305255)
#### Image of successful build on travis.
image

### CODE REVIEW

**Review by AlvinMugambi — COMMENTED** [review]
Great work. You can look to add `after_success: coveralls` in the travis.yml so that coveralls is updated after travis builds.

**Comment by katherine95** [comment]
> Great work. You can look to add `after_success: coveralls` in the travis.yml so that coveralls is updated after travis builds.

Thank you for feedback. I have added the command

**Review by AlvinMugambi — APPROVED** [review]
Great.

**Review by Benkimeric — APPROVED** [review]

**Comment by ElishaMisoi** [comment]
Looks good to me 👍🏽

**Review by ElishaMisoi — APPROVED** [review]

**Review by rnjane — APPROVED** [review]

**Review by rnjane — CHANGES_REQUESTED** [review]
@katherine95 your changes are conflicting with the current develop. Kindly resolve the conflicts.

**Comment by katherine95** [comment]
> @katherine95 your changes are conflicting with the current develop. Kindly resolve the conflicts.

Done.

**Pull request merged**
