### PR TITLE
#165305251 Upgrade Django app from Django 1.10 to Django 2.1

### PR DESCRIPTION
**Pull request by jkamz**
### What does this PR do?
Upgrade Django from version 1.10 to 2.1

### Description of Task(s) to be completed?

Upgrade Django from v1.10 to v2.1
Upgrade all other django extensions and django rest to latest versions
Update url patterns to include features included in Django 2.1 that were not in Django 1.0

### How should this be manually tested?

Clone this repository on local machine and CD into project folder

`$ git clone git@github.com:andela/ah-the-jedi-backend.git`
`$ cd ah-the-jedi-backend`

Check out to the PR's branch

`$ git checkout ch-upgrade-django-165305251`

Create and activate virtual environment

`$ python3 -m venv venv`
`$ source .venv/bin/activate`

Install app dependencies from requirements.txt

`$ pip install -r api/requirements.txt`

Check the versions of the installed packages

`$ pip freeze`

### What are the relevant Pivotal Tracker stories?
[165305251](https://www.pivotaltracker.com/story/show/165305251)

### Screenshots

image

### CODE REVIEW

**Comment by MisoiElisha** [comment]
Looks good to me. Keep up.

**Review by MisoiElisha — APPROVED** [review]

**Review by AlvinMugambi — APPROVED** [review]
Good work.

**Review by Benkimeric — APPROVED** [review]
Nice implementation

**Review by Siffersari — APPROVED** [review]
I love how well formatted your PR is. Good job resolving the errors that come with version mismatch of other dependencies.

**Comment by ElishaMisoi** [comment]
@jkamz Add the relevant PT Story in your PR.

**Comment by jkamz** [comment]
> @jkamz Add the relevant PT Story in your PR.

Done. Thanks.

**Review by ElishaMisoi — APPROVED** [review]

**Review by katherine95 — APPROVED** [review]

**Comment by rnjane** [comment]
👍

**Pull request merged**
