### PR TITLE
#165305260 Implement JSON Web Token based authentication

### PR DESCRIPTION
**Pull request by jkamz**
### What does this PR do?
Implements token based authentication in the app

### Description of Task(s) to be completed?
- implement means to generate jwt token
- ensure a token is returned after successful account activation
- ensure a token is returned after successful login
- update tests to incorporate the implemented jwt authentication configuration
- Add tests to ensure a valid token is returned on successful account activation and login

### How should this be manually tested?

Clone this repository on local machine and CD into project folder
`$ git clone git@github.com:andela/ah-the-jedi-backend.git`
`$ cd ah-the-jedi-backend`

Check out to the PR's branch
`$ git checkout ft-jwt-authentication-165305260`

Create and activate virtual environment
`$ python3 -m venv venv`
`$ source .venv/bin/activate`

Install app dependencies from requirements.txt
`$ pip install -r api/requirements.txt`

Make migrations and run the server
`$ python manage.py makemigrations`
`$ python manage.py migrate`
`$ python manage.py runserver`

Use postman to test the user activation and login endpoints

The responses to the above requests should contain a token as shown in the screenshots below

### What are the relevant PT stories?
[165305260](https://www.pivotaltracker.com/story/show/165305260)

#### activation
image

#### login
Screenshot 2019-04-29 at 01 39 44

### CODE REVIEW

**Comment by ElishaMisoi** [comment]
I am of the opinion that the jwt token should be generated on successful login only as opposed to both on account activation and login.

**Comment by katherine95** [comment]
> I am of the opinion that the jwt token should be generated on successful login only as opposed to both on account activation and login.

Sure. I second this as it will make use of activation of an account feature.

**Review by katherine95 — APPROVED** [review]

**Comment by Benkimeric** [comment]
> I am of the opinion that the jwt token should be generated on successful login only as opposed to both on account activation and login.

Nice implementation @jkamz , however, I support this suggestion from @Elisha-Misoi

**Comment by rnjane** [comment]
@katherine95 @Elisha-Misoi I am in contact with the PO to know how to implement this, because as of now, the story is conflicting with #9 implementation.
Will let you all know what we decide on

**Comment by Siffersari** [comment]
Good Implementation John. I second also @Elisha-Misoi. Due to the need to activate an account before logging in.

**Comment by rnjane** [comment]
Just got feedback from the P.O,
We'll generate JWT authentication tokens upon email verification and user login only, and not on user signup. @jkamz kindly re-implement this using this criterion.

**Review by rnjane — CHANGES_REQUESTED** [review]
We'll generate JWT authentication tokens upon email verification and user login only, and not on user signup. @jkamz kindly re-implement this using this criterion.

**Review by Siffersari — APPROVED** [review]
LGTM

**Review by Benkimeric — APPROVED** [review]
Looks good to me.

**Comment by AlvoMugz** [comment]
Looks good to me. You can look to update the screenshots with the new inplementation.

**Review by ElishaMisoi — APPROVED** [review]

**Review by katherine95 — APPROVED** [review]
LGTM. Great work in ensuring an access token is received after activation.

**Review by AlvoMugz — APPROVED** [review]

**Review by rnjane — APPROVED** [review]

**Pull request merged**
