### PR TITLE
#165305264 Enable social login via Facebook, Twitter and Google.

### PR DESCRIPTION
**Pull request by katherine95**
#### What does this PR do?
Enable social login via Facebook, Twitter, and Google.
#### Description of Task to be completed?
- Implement Facebook's, Twitter's, and Google's API to allow a user to log in using either of their existing accounts
- Give the logged in user our application's JWT token.
- Write tests for the implementation.
#### How should this be manually tested?
Ensure you have the below variables in your environment.
- TWITTER_KEY=<twitter_key>
- TWITTER_SECRET=<twitter_secret>
- FACEBOOK_APP_ID=<facebook_app_id>
- FACEBOOK_SECRET_KEY=<facebook_secret_key>
- GOOGLE_CLIENT_ID= <google_client_id>
- GOOGLE_CLIENT_SECRET=<google_client_secret>
1. Clone this repo.
   `git clone https://github.com/andela/ah-the-jedi-backend.git`
2. Fetch all origin to get all branches
   `git fetch origin`
3. Checkout to `ft-enable-social-login-165305264` branch.
   `git checkout ft-enable-social-login-165305264`
4. Activate `virtualenv`
    `$ virtualenv -p python .venv`
    `$ source .venv/bin/activate`
5. Install requirements
   `$ pip install -r requirements.txt`
6. Start server
   `$ python api/manage.py runserver`
7. Test the endpoint on postman in the following steps:
- `POST /api/users/social/login/`
- Test Facebook login -> Enter provider as `facebook` and Facebook's user access token.
- Test Twitter login -> Enter provider `twitter` and Twitter's user access token and access token secret.
- Test Google login -> Enter provider as `google-oauth2` and Google's user id_token
- Use the generated JWT token to authorize the user and access protected endpoints.
#### What are the relevant pivotal tracker stories?
[#165305264](https://www.pivotaltracker.com/story/show/165305264)
#### Screenshot
Facebook Login
Screenshot 2019-05-01 at 12 55 17

Twitter Login
Screenshot 2019-05-01 at 12 57 41

Google Login
Screenshot 2019-05-01 at 13 13 19

Invalid Token
Screenshot 2019-05-01 at 13 42 09

### CODE REVIEW

**Review by Siffersari — APPROVED** [review]
LGTM

**Review by ElishaMisoi — APPROVED** [review]
LGTM

**Review by jkamz — APPROVED** [review]
LGTM. Good work.

**Review by AlvinMugambi — APPROVED** [review]

**Review by Benkimeric — APPROVED** [review]
Nice implementation @katherine95.  LGTM

**Review by rnjane — APPROVED** [review]

**Pull request merged**
