### PR TITLE
#165305269 Users should be able to like and or dislike articles

### PR DESCRIPTION
**Pull request by Benkimeric**
### What does this PR do?
- Adds the ability to like and dislike articles

### Description of the task to be completed?
- Users should be able to like and or dislike articles
- Add tests for the functionality

### How should you manually test this?

- [x] **Clone the repository**

        $ git clone https://github.com/andela/ah-the-jedi-backend.git

- [x] **Switch to testing branch**

       $ git checkout ft-like-dislike-articles-165305269

- [x] **Switch to the parent directory**

       $ cd ah-the-jedi-backend/

 

- [x] **Create and activate the virtual environment**

      $  virtualenv -p python .venv

      $ source .venv/bin/activate

- [x] **Install project dependencies**

       $ pip install -r api/requirements.txt

- [x] **Run the database migrations**

       $ python api/manage.py migrate

### Running the application

      $ python api/manage.py runserver

- [x] **Signup and activate user**

           POST <your-localhost>/api/users/

           Creates a user profile on successful signup

- [x] **Login user**

       POST <your-localhost>/api/login/ 

       Use the token provided after login for Authorization and the endpoint
  
- [x] **Create an article record**

      POST <your-localhost>/api/articles/

- [x] **Like an article**

     POST Like an article endpoint `<you-local-host>/api/articles/{article-slug}/like/`

- [x] **Disike an article**

    POST Disike an article endpoint `<you-local-host>/api/articles/{article-slug}/dislike/`

### Testing

      $ python api/manage.py test

### Prerequisites

Python, Git,  Virtualenv

### What are the relevant PT stories?

[#165305269](https://www.pivotaltracker.com/story/show/165305269)

### Successful Liking on an article
Screenshot 2019-05-06 at 13 05 02

### Successful Disliking an article
Screenshot 2019-05-06 at 13 05 30

### Counting for number of like and dislikes
Screenshot 2019-05-06 at 13 22 34

### CODE REVIEW

**Review by ElishaMisoi — APPROVED** [review]

**Review by Siffersari — COMMENTED** [review]
Lines 24 - 26 are covered in the BaseTest. They can be removed. 

You could also move create_articles method, lines 38 - 47, to the BaseTest so that it can be used by others also.

**Comment by Benkimeric** [comment]
> Lines 24 - 26 are covered in the BaseTest. They can be removed.
> 
> You could also move create_articles method, lines 38 - 47, to the BaseTest so that it can be used by others also.

Done.

**Review by Siffersari — APPROVED** [review]
Good implementation for like and dislike features.

**Review by katherine95 — APPROVED** [review]
LGTM

**Review by AlvinMugambi — APPROVED** [review]
LGTM

**Review by rnjane — APPROVED** [review]

**Pull request merged**
