### PR TITLE
#165305248 Write unit tests for all functionality

### PR DESCRIPTION
**Pull request by Siffersari**
### What does this PR do?

Adds unit tests for all implemented functionality

### Description of the task to be completed?

- Add unit test for Signup, Login, Fetching and Updating user data

### How should you manually test this?

- [x] **Clone the repository**

        $ git clone https://github.com/andela/ah-the-jedi-backend.git

- [x] **Switch to testing branch**

       $ git checkout ch-add-functionality-tests-165305248 

- [x] **Switch to the ah-the-jedi-backend directory**

       $ cd ah-the-jedi-backend/

 

- [x] **Create and activate the virtual environment**

      $  virtualenv -p python .venv

      $ source .venv/bin/activate

- [x] **Install project dependencies**

       $ pip install -r requirements.txt

- [x] **Run the database migrations**

       $ python manage.py migrate

### Running the application

      $ python manage.py runserver

- [x] **Signup and activate user**

           POST <your-localhost>/api/signup/

- [x] **Login user**

       POST <your-localhost>/api/login/ 

  
- [x] **Fetch a user  details**

     

      GET <your-localhost>/api/user

Basic Authentication required

- [x] **Update user details**

       PUT <your-localhost>/api/user

Basic Authentication required

### Testing

      $ python manage.py test

### Prerequisites

Python, Git,  Virtualenv

### What are the relevant PT stories?

[#165305248](https://www.pivotaltracker.com/story/show/165305248)

### Screenshots

Screenshot 2019-04-24 at 12 21 15

### CODE REVIEW

**Comment by katherine95** [comment]
Great job. Include a screenshot on tests running for the functionality tests.

**Review by AlvinMugambi — APPROVED** [review]
Looks good to me

**Review by ElishaMisoi — APPROVED** [review]
LGTM 👍🏽

**Review by jkamz — APPROVED** [review]

**Comment by jkamz** [comment]
LGTM

**Comment by katherine95** [comment]
LGTM. Great work on testing for error messages and data alongside status codes.

**Review by rnjane — APPROVED** [review]

**Pull request merged**
